english_dictionary/urls.py
from django.contrib import admin
from rest_framework import routers
from django.urls import path, include
from django.views.generic import RedirectView
from dictionary.views import WordViewSet, LevelViewSet, CategoryViewSet

router = routers.DefaultRouter()
router.register(r'word', WordViewSet)
router.register(r'level', LevelViewSet)
router.register(r'category', CategoryViewSet)

urlpatterns = [
    path('', RedirectView.as_view(url='admin/')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/v1/', include(router.urls), name='api'),
]

dictionary/models.py
from django.db import models
from django.conf import settings


class Category(models.Model):
    name = models.CharField(max_length=50, help_text="Ex. Money")

    def __str__(self):
        return '{}'.format(self.name)


class Level(models.Model):
    name = models.CharField(max_length=50, help_text="Ex. B1.2")

    def __str__(self):
        return '{}'.format(self.name)


class Word(models.Model):
    english_word = models.CharField(max_length=60, help_text="Ex. Travel")
    spanish_word = models.CharField(max_length=100, help_text="Ex. Viajar")
    spanish_pronunciation = models.CharField(max_length=60,
                                             help_text="Ex. trável (puedes usar las tildes para acentuar donde se hace el énfasis en la pronunciación)",
                                             null=True, blank=True)
    phonetics = models.CharField(max_length=60,
                                 help_text="Ex. /ˈtræv(ə)l/. Get it on: https://dictionary.cambridge.org/es/",
                                 null=True, blank=True)
    notes = models.TextField(max_length=settings.DEFAULT_TEXTAREA_SIZE,
                             help_text="Ex. Suele usarse como verbo, rara como sustantivo o adjetivo", null=True,
                             blank=True)
    is_important = models.BooleanField(default=False, help_text="This word has extra score for exams in the same level")
    category = models.ManyToManyField(Category)
    level = models.ForeignKey(Level, on_delete=models.CASCADE, default=2)

    def get_categories(self):
        return ", ".join([l.name for l in self.category.all()])

    def __str__(self):
        return 'Word({} - {})'.format(self.english_word, self.spanish_word)

commons/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "commons/dashboard.html"
    redirect_field_name = 'redirect_to'
    login_url = 'login'

dictionary/views.py
from django_filters import CharFilter
from django_filters.rest_framework import DjangoFilterBackend, FilterSet
from rest_framework import viewsets, permissions, mixins
from rest_framework.filters import OrderingFilter

from .serializers import *
from .models import *


# FILTERS
class WordFilter(FilterSet):
    english_word_contains = CharFilter(field_name="english_word", lookup_expr='contains')
    spanish_word_contains = CharFilter(field_name="spanish_word", lookup_expr='contains')

    class Meta:
        model = Word
        fields = ["english_word_contains", "spanish_word_contains", "category"]


# VIWSETS
class LevelViewSet(mixins.CreateModelMixin,
                    mixins.RetrieveModelMixin,
                    mixins.ListModelMixin,
                    viewsets.GenericViewSet):
    permission_classes = (permissions.IsAdminUser,)
    queryset = Level.objects.all()
    serializer_class = LevelSerializer


class CategoryViewSet(mixins.CreateModelMixin,
                    mixins.RetrieveModelMixin,
                    mixins.ListModelMixin,
                    viewsets.GenericViewSet):
    # If we add: mixins.DestroyModelMixin,
    # we also could delete categories
    permission_classes = (permissions.IsAdminUser,)
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class WordViewSet(viewsets.ModelViewSet):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    queryset = Word.objects.all()
    serializer_class = WordSerializer
    filter_backends = (DjangoFilterBackend, OrderingFilter,)
    filter_class = WordFilter
    ordering_fields = ("english_word", "spanish_word", "category",)
    ordering = ("category",)

commons/templates/commons/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Meta -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <!-- /Meta -->
  <!-- Icons -->
  <link rel="shortcut icon" href="{% static "commons/images/icons/icon.ico" %}" type="image/x-icon">
  <link rel="icon" href="{% static "commons/images/icons/icon.png" %}">
  <link rel="icon" sizes="32x32" href="{% static "commons/images/icons/icon-32x32.png" %}">
  <link rel="icon" sizes="57x57" href="{% static "commons/images/icons/icon-57x57.png" %}">
  <link rel="icon" sizes="72x72" href="{% static "commons/images/icons/icon-72x72.png" %}">
  <link rel="icon" sizes="76x76" href="{% static "commons/images/icons/icon-76x76.png" %}">
  <link rel="icon" sizes="96x96" href="{% static "commons/images/icons/icon-96x96.png" %}">
  <link rel="icon" sizes="114x114" href="{% static "commons/images/icons/icon-114x114.png" %}">
  <link rel="icon" sizes="128x128" href="{% static "commons/images/icons/icon-128x128.png" %}">
  <link rel="icon" sizes="144x144" href="{% static "commons/images/icons/icon-144x144.png" %}">
  <link rel="icon" sizes="152x152" href="{% static "commons/images/icons/icon-152x152.png" %}">
  <link rel="icon" sizes="192x192" href="{% static "commons/images/icons/icon-192x192.png" %}">
  <link rel="icon" sizes="384x384" href="{% static "commons/images/icons/icon-384x384.png" %}">
  <link rel="icon" sizes="512x512" href="{% static "commons/images/icons/icon-512x512.png" %}">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- /Icons -->
  <title>English Dictionary Intermediate 1 {% block title %}{% endblock title %}</title>
  <link rel="manifest" href="{% static "commons/manifest.json" %}">
  <!-- Plugins -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.16/b-1.5.1/b-html5-1.5.1/b-print-1.5.1/r-2.2.1/datatables.min.css"/>
  <!-- /Plugins -->
  <!-- Custom Styles -->
  <link rel="stylesheet" href="{% static "commons/css/commons.css" %}">
  <!-- /Custom Styles -->
</head>
<body>
  {% if user.is_authenticated %}
  <header>
    <nav class="light-blue lighten-1">
      <div class="nav-wrapper">
        <a href="{% url 'dashboard' %}" class="brand-logo center">
          <img src="{% static "commons/images/icons/icon-32x32.png" %}" class="circle responsive-img" alt="Logo" title="English Intermediate 1">
        </a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="hide-on-med-and-down">
          <li><a href="{% url 'words_list' %}">Words</a></li>
          <li><a href="{% url 'words_create' %}">New word</a></li>
          <li><a href="{% url 'logout' %}" class="right">Logout</a></li>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><a href="{% url 'words_list' %}">Words</a></li>
          <li><a href="{% url 'words_create' %}">New word</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
        </ul>
      </div>
    </nav>
  </header>
  {% endif %}
  <main class="container">
    <section class="row">
      <div class="col s12">
        {% block content %}
        <h1>HELLO WORLD!!</h1>
        {% endblock content %}
      </div>
    </section>
  </main>
  <!-- Plugins -->
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  <!-- Datatables -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.16/b-1.5.1/b-html5-1.5.1/b-print-1.5.1/r-2.2.1/datatables.min.js"></script>
  <!-- Datatables -->
  <!-- /Plugins -->
  <script src="{% static "commons/js/commons.js" %}"></script>
  {% block js_scripts %}{% endblock js_scripts %}
</body>
</html>

commons/templates/commons/dashboard.html
{% extends 'commons/base.html' %}

{% block title %}- Dashboard{% endblock title %}

{% block content %}
<h1>English Dictionary: Intermediate 1</h1>
<h3>HELLO <span class="light-blue-text text-lighten-1">{{ user.get_username }}</span>!!!</h3>
<p>If you want to see a <strong>full</strong> words list, please click the <strong>"Words"</strong> option inside the menu.</p>
<p>Also, you can add or edit words inside the same menu option.</p>
{% endblock content %}

dictionary/templates/dictionary/word_confirm_delete.html
{% extends 'commons/base.html' %}

{% block title %}- Delete {{ object.english_word }}{% endblock title %}

{% block content %}
<h1>Delete Word</h1>
<section class="pretty-top">
  <p>Are you sure you want to delete "{{ object.english_word }}"?</p>
  <hr>
  {% if form.errors %}
  <div class="col s12 red-text">
    {{ form.errors }}
  </div>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <button type="submit" class="col s12 red waves-effect waves-light btn-large">Confirm</button>
  </form>
</section>
{% endblock content %}

dictionary/templates/dictionary/word_detail.html
{% extends 'commons/base.html' %}

{% block title %}- Word Detail{% endblock title %}

{% block content %}
<section class="pretty-top">
  <h1>Word Detail</h1>
  <section class="col s12 card bordered">
    <div class="card-content">
      <span class="card-title">English word</span>
      <div class="divider"></div>
      <p class="section">{{ object.english_word }}</p>
    </div>
  </section>

  <section class="col s12 card bordered">
    <div class="card-content">
      <span class="card-title">Spanish word</span>
      <div class="divider"></div>
      <p class="section">{{ object.spanish_word }}</p>
    </div>
  </section>

  <section class="col s12 card bordered">
    <div class="card-content">
      <span class="card-title">Spanish pronunciation</span>
      <div class="divider"></div>
      <p class="section">{{ object.spanish_pronunciation }}</p>
    </div>
  </section>

  <section class="col s12 card bordered">
    <div class="card-content">
      <span class="card-title">Phonetics</span>
      <div class="divider"></div>
      <p class="section">{{ object.phonetics }}</p>
    </div>
  </section>

  <section class="col s12 card bordered">
    <div class="card-content">
      <span class="card-title">Note</span>
      <div class="divider"></div>
      <p class="section">{{ object.notes }}</p>
    </div>
  </section>

  <section class="col s12 card bordered">
    <div class="card-content">
      <span class="card-title">Category</span>
      <div class="divider"></div>
      <p class="section">{{ object.category }}</p>
    </div>
  </section>
</section>
{% endblock content %}

dictionary/templates/dictionary/word_form.html
{% extends 'commons/base.html' %}

{% block title %}- New Word{% endblock title %}

{% block content %}
<h1>{{ header_text|default:"Word" }}</h1>
<section class="pretty-top">
  {% if form.errors %}
  <div class="col s12 red-text">
    {{ form.errors }}
  </div>
  {% endif %}
  <form class="col s12" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div class="row">
      {% if field.errors %}
      <div class="red-text">
        {{ field.errors }}
      </div>
      {% endif %}
      <div class="input-field col s12">
        <label for="{{ field.name }}" class="active">{{ field.label }}</label>
        {{ field }}
        {% if field.help_text %}
        <span class="helptext">{{ field.help_text|safe }}</span>
        {% endif %}
      </div>
    </div>
    {% endfor %}
    <button type="submit" class="col s12 waves-effect waves-light btn-large">
      <i class="material-icons left">save</i>
      Save
      <i class="material-icons right">save</i>
    </button>
  </form>
</section>
{% endblock content %}

{% block js_scripts %}
<script>
var myResponseFunction = function (data) {
  $('#response').html('data: ' + JSON.stringify(data));
};

// Creamos la funcion y le agregamos el parametro callback
// (ademas de otros que pueda necesitar)
function myAJAXFunction(event) {
    $.ajax({
        method: 'POST',
        url: '/echo/json/',
        dataType: 'json',
        data: {
            json: JSON.stringify({
                'foo': 'bar'
            })
        }
    }).done(function(response) {
      // Una vez se raliza la peticion devolvemos la respuesta
      myResposeFunction(response);
    }).fail(function (jqXHR, textStatus, errorThrown) {
      window.console.error('Error ' + textStatus + ': ' + errorThrown);
    });
}

// Invocamos a la funcion que hace la llamada AJAX y
// le pasamos como parametro la funcion que gestionara la respuesta AJAX
$('#button').on('click', myAJAXFunction);

$.ajax({
    "url": "your_url_here",
    "method": "GET",
    "data": $.param({}),
    "dataType": "json",
    "timeout": 30000 // 30 seconds
}).done(function (response) {
    try {
        if (response.ok) {
            window.console.log(response);
        } else {
            throw response.error;
        }
    } catch (err) {
        window.alert("Error");
        window.console.error('Error: ' + err);
    }
}).fail(function (jqXHR, textStatus, errorThrown) {
    window.alert("Error");
    window.console.error(textStatus + ': ' + errorThrown);
});

  $(document).ready(function() {
    function capitalizeFirstWord(text) {
      return text.charAt(0).toUpperCase() + text.slice(1);
    }

    $("form").on("submit", function(ev) {
      document.getElementById("id_english_word").value = capitalizeFirstWord(document.getElementById("id_english_word").value);
      document.getElementById("id_spanish_word").value = capitalizeFirstWord(document.getElementById("id_spanish_word").value);
      document.getElementById("id_spanish_pronunciation").value = capitalizeFirstWord(document.getElementById("id_spanish_pronunciation").value);
      document.getElementById("id_phonetics").value = capitalizeFirstWord(document.getElementById("id_phonetics").value);
      document.getElementById("id_notes").value = capitalizeFirstWord(document.getElementById("id_notes").value);
    });
  });
</script>
{% endblock js_scripts %}

dictionary/templates/dictionary/words_list.html
{% extends 'commons/base.html' %}

{% block title %}- Words{% endblock title %}

{% block content %}
<h1>Words</h1>
<section class="pretty-top">
  <div class="row">
    <div class="col s12">
      <a href="./create/" class="lime darken-3 waves-effect waves-light btn btn-large">Add new word</a>
    </div>
  </div>
  <div class="row">
    <div class="col s12">
      <table class="datatables display">
        <thead>
          <tr>
            <th>English word</th>
            <th>Spanish word</th>
            <th>Spanish pronunciation</th>
            <th>Phonetics</th>
            <th>Notes</th>
            <th>Category</th>
            <th>Level</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for element in object_list %}
          <tr>
            <td>{{ element.english_word }}</td>
            <td>{{ element.spanish_word }}</td>
            <td>{{ element.spanish_pronunciation }}</td>
            <td>{{ element.phonetics }}</td>
            <td>{{ element.notes|truncatewords_html:8 }}</td>
            <td>
              {% for category in element.category.all %}
                {{ category }}{% if not forloop.last %},{% endif %}
              {% endfor %}
            </td>
            <td>{{ element.level }}</td>
            <td>
                {# {{ element.category_set.all }} #}
              <a href="./detail/{{  element.pk  }}" class="green-text">
                <i class="material-icons">visibility</i>
              </a>
              <a href="./update/{{ element.pk }}" class="orange-text">
                <i class="material-icons">mode_edit</i>
              </a>
              {% ifequal user.groups.all.0.name 'Teachers' %}
              <a href="./delete/{{ element.pk }}" class="red-text">
                <i class="material-icons">delete</i>
              </a>
              {% endifequal %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m3">
      <a href="./create/" class="lime darken-3 waves-effect waves-light btn btn-large">Add new word</a>
    </div>
    {% if is_paginated %}
    <div class="col s12 m9">
      <ul class="pagination right-align">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}" class="waves-effect"><i class="material-icons">chevron_left</i></a></li>
        {% else %}
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
        {% endif %}
        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="active"><a href="#!">{{ i }}</a></li>
        {% else %}
        <li class="waves-effect"><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}" class="waves-effect"><i class="material-icons">chevron_right</i></a></li>
        {% else %}
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
        {% endif %}
      </ul>
    </div>
    {% endif %}
  </div>
</section>
{% endblock content %}